# Generated by Django 5.1.3 on 2024-12-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_offers_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile",
            field=models.ImageField(blank=True, null=True, upload_to="profile"),
        ),
    ]
