# Generated by Django 5.1.3 on 2024-12-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile",
            field=models.ImageField(
                blank=True,
                default="static/img/user_default.png",
                null=True,
                upload_to="profile",
            ),
        ),
    ]
