# Generated by Django 5.1.3 on 2024-12-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RentedCostumes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=200)),
                ("material", models.CharField(max_length=300)),
                ("description", models.CharField(max_length=300)),
                ("image", models.ImageField(upload_to="coustume_images")),
                ("total_stock", models.PositiveBigIntegerField(default=0)),
                ("per_date_price", models.PositiveBigIntegerField()),
                ("size", models.CharField(max_length=100)),
                ("colour", models.CharField(max_length=200)),
                (
                    "costume_categories",
                    models.CharField(
                        choices=[
                            ("trending costumes", "Trending Costumes"),
                            ("casual costumes", "Casual Costumes"),
                            ("formals costumes", "formals Costumes"),
                            ("dance costumes", "dance Costumes"),
                        ],
                        max_length=200,
                    ),
                ),
            ],
        ),
    ]
