# Generated by Django 5.1.3 on 2024-12-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coustumes", "0002_rename_total_stock_rentedcostumes_xl_size_stock_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentedcostumes",
            name="costume_categories",
            field=models.CharField(
                choices=[
                    ("trending costumes", "Trending Costumes"),
                    ("casual costumes", "Casual Costumes"),
                    ("formal costumes", "Formals Costumes"),
                    ("dance costumes", "Dance Costumes"),
                    ("party wear", "Party wear"),
                    ("sweater", "Sweater"),
                ],
                max_length=200,
            ),
        ),
    ]
