# Generated by Django 5.1.3 on 2024-12-10 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coustumes", "0003_alter_rentedcostumes_costume_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingRentedCostumes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booked_date", models.DateTimeField(auto_now=True)),
                ("pairs", models.PositiveBigIntegerField(blank=True, null=True)),
                ("price", models.PositiveBigIntegerField(blank=True, null=True)),
                ("return_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("undelivered.", "undelivered"),
                            ("return", "Return"),
                            ("completed.", "Completed"),
                        ],
                        default="undelivered",
                        max_length=200,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "username",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
