# Generated by Django 5.1.3 on 2024-12-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coustumes", "0004_bookingrentedcostumes"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingrentedcostumes",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="coustumes.rentedcostumes",
            ),
        ),
    ]
