# Generated by Django 5.1.3 on 2024-12-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coustumes", "0005_bookingrentedcostumes_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingrentedcostumes",
            name="item",
        ),
        migrations.AddField(
            model_name="bookingrentedcostumes",
            name="item",
            field=models.ManyToManyField(to="coustumes.rentedcostumes"),
        ),
    ]
