# Generated by Django 5.1.3 on 2024-12-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coustumes", "0008_dresscode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dresscode",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="dress_image"),
        ),
    ]
