# Generated by Django 5.1.3 on 2024-12-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coustumes", "0009_alter_dresscode_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="dresscode",
            name="outfit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("shirt", "Shirt"),
                    ("t shirt", " T Shirt"),
                    ("kurtha", "Kurtha"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dresscode",
            name="respond",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
