# Generated by Django 5.1.3 on 2024-12-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coustumes", "0010_dresscode_outfit_type_dresscode_respond"),
    ]

    operations = [
        migrations.AddField(
            model_name="dresscode",
            name="quantity",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
